name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}-${{ github.event_name == 'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Cody AI Code Review Tool
        uses: codylabs/cody-code-reviewer@master
        with:
          pr_number: ${{ github.event.pull_request.number }}
          repository: ${{ github.repository }}
        env:
          # This is provided by default, you do not need to change this
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Update the below in your GitHub repo actions secrets to use your OpenAI API key
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Update the below to use the model of your choice
          OPENAI_MODEL: "gpt-4o"
