name: Automated Code Review by Cody

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone Cody Code Reviewer Repository
        run: |
          git clone https://github.com/codylabs/cody-code-reviewer.git cody-code-reviewer

      - name: Run Code Review Model
        run: |
          python cody-code-reviewer/src/review_pull_request.py ${{ github.event.pull_request.number }} ${{ github.repository }} > ${{ github.workspace }}/output.txt
        env:
          # This is provided by default, you do not need to change this
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Update the below in your GitHub repo actions secrets to use your OpenAI API key
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Update the below to use the model of your choice
          OPENAI_MODEL: "gpt-4o"

      - name: Display Review Result
        run: |
          printf "Review result:\n%s" "${{ env.REVIEW_RESULT }}"

      - name: Comment on Pull Request
        if: failure() # Runs if any of the previous steps failed
        run: |
          python cody-code-reviewer/src/comment_on_pr.py ${{ github.event.pull_request.number }} "${{ secrets.GITHUB_TOKEN }}" ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pull-requests: write
